Fix TypeError: 'str' does not support the buffer interface
```python
C:\python34\python.exe savacli.py -c savacli.conf -r -i C:\Downloads\
Traceback (most recent call last):
  File "savacli.py", line 900, in <module>
    exit_code = main()
  File "savacli.py", line 819, in main
    scanner.scan(entry)
  File "savacli.py", line 395, in scan
    self.__proto.scan(path)
  File "savacli.py", line 62, in wrapper
    result = f(*p, **kw)
  File "savacli.py", line 238, in scan
    alert_name, status, description = message.split(";")
TypeError: 'str' does not support the buffer interface
```